###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# Build Info
###############################################################################
Build=@BUILD@

###############################################################################
# General Info
###############################################################################
ReportWizardDescription=Cet assistant crée un nouvel état à partir d'un modèle prédéfini.
ReportProjectWizardDescription=Crée un projet d'état.
ReportPerspective=Modèle d'état
ReportViews=Modèle d'état
WizardCategoryName=Outils de reporting et de Business Intelligence
ReportWizard=Etat
ReportProjectWizard=Projet d'état
ReportEditor=Editeur d'état
QuickEditView=Editeur de propriétés
DataExplorerView=Explorateur de données
cheatsheet.category=Outils de reporting et de Business Intelligence
cheatsheet.simplelisting=Etat - Listes simples
cheatsheet.groupedlisting=Etat - Listes groupées
cheatsheet.dualcolumnlisting=Etat - Listes de colonnes doubles
cheatsheet.chartlisting=Etat - Graphiques et listes
cheatsheet.sidebysidechartlisting=Etat - Graphiques et listes juxtaposés
cheatsheet.dualcolumnchartlisting=Etat - Graphiques et listes de colonnes doubles
cheatsheet.firstreport=Mon premier état

###############################################################################
# UI Framework
###############################################################################
designer.ui.extensionPointName=Interface utilisateur - Elément d'état étendu

preference.birt=Modèle d'état
preference.datasetpreview=Editeur de jeu de données
preference.preview=Aperçu
preference.preview.server=Serveur de prévisualisation
preference.elementnames=Noms des éléments
preference.library=Bibliothèque
preference.template=Modèle
preference.resource=Ressource
preference.commenttemplates=Modèle de commentaire

designer.action.undo.label=Annuler
designer.action.redo.label=Rétablir

extension.odadatasource=Point d'extension de la source de données ODA

publish.template=Publier dans le dossier modèle...
publish.library=Publier la bibliothèque dans le dossier de ressources...

ActionSet.Publish=Publier
